spring.application.name=grog

# ????????? ??????????? ? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/your_defectdojo_db_name
spring.datasource.username=your_db_username
spring.datasource.password=your_db_password
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????? JPA / Hibernate
# ddl-auto=create-drop - ??????? ??????? ??? ??????, ??????? ??? ?????????? (?????? ??? ????????????!)
# ddl-auto=update - ????????? ?????, ???? ??? ?????????? (???????? ??? ??????????)
# ddl-auto=validate - ????????? ?????, ?? ?????? ??
# ddl-auto=none - ?? ?????? ?????
# ??? ??????? ??????? ? ???????????? ???????? update
spring.jpa.hibernate.ddl-auto=update
# ?????????? SQL-??????? ? ???? (??????? ??? ???????)
spring.jpa.show-sql=true
# ????????????? SQL-??????? (??? ?????????? ? ????)
spring.jpa.properties.hibernate.format_sql=true

# ???????????: ??????????? SQL-???????? ?? ?????? TRACE
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE